# Generated by Django 5.2.12 on 2026-05-05 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('author', models.CharField(max_length=160)),
                ('isbn', models.CharField(blank=True, max_length=32)),
                ('category', models.CharField(default='General', max_length=100)),
                ('shelf_location', models.CharField(blank=True, max_length=60)),
                ('total_copies', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='tenants.tenant')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
