# Generated by Django 5.2.12 on 2026-05-05 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('subscription_plan', models.CharField(choices=[('basic', 'Basic'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='growth', max_length=20)),
                ('borrowing_days', models.PositiveSmallIntegerField(default=5)),
                ('max_renewals', models.PositiveSmallIntegerField(default=2)),
                ('reservation_limit', models.PositiveSmallIntegerField(default=10)),
                ('fine_per_day', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LibraryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('librarian', 'Librarian'), ('member', 'Member')], max_length=20)),
                ('student_id', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'email')},
            },
        ),
    ]
